var betaTesters = [
    "Notobiv",
    "Thomas Butler",
    "Kribit",
    "Kate Butler",
    "Oliver Butler",
    "Simon Butler",
    "God NTSC Player",
    "Haven Wenzel",
    "ppougj Gaming",
    "Ty Cirino",
    "Braxton McFarland",
    "Smooshymemes",
    "Larry the Hamster",
    "Pompelo",
    "Annoying Dog",
    "Matt Quinn",
    "Josiah Sage",
    "James Butler",
    "CarsonPlay2",
    "Sharon Butler",
    "William Butler",
    "Dakota Reinikka",
    "Adrian Falcon",
    "Matthew Ritchey",
    "Okman241",
    "Mosh",
    "Qatt",
    "Jakem",
    "Arctic",
    "Dxtr",
    "Brain Washed",
    "GHY",
    "Kabez",
    "Jbg Goat"
];